# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SMSPackageDetails',
            fields=[
                ('packageId', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=60)),
                ('commertial_model', models.CharField(choices=[('Buy', 'Buy'), ('TryNBuy', 'TryNBuy'), ('Free', 'Free')], default='Buy', max_length=30)),
                ('contentType', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD')], default='SD', max_length=30)),
                ('coupansApplicable', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD')], default='SD', max_length=30)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('packDuration', models.IntegerField()),
                ('packType', models.CharField(choices=[('topup', 'topup'), ('standard', 'standard'), ('offer', 'offer'), ('partnerAutoActivate', 'partnerAutoActivate'), ('trialOffer', 'trialOffer')], default='topup', max_length=30)),
                ('subscriptionType', models.CharField(choices=[('SVOD', 'SVOD'), ('TVOD', 'TVOD')], default='SVOD', max_length=30)),
                ('packPremium', models.CharField(choices=[('Ad', 'Ad'), ('No Ad', 'No Ad')], default='No Ad', max_length=30)),
                ('consumptionType', models.CharField(choices=[('Stream', 'Stream'), ('Download', 'Download'), ('All', 'All')], default='Stream', max_length=30)),
                ('downloadType', models.CharField(choices=[('off-peak', 'off-peak'), ('off-line', 'off-line'), ('Immediate', 'Immediate')], default='Immediate', max_length=30)),
                ('description', models.TextField()),
                ('packDataValue', models.IntegerField()),
                ('assetGroupId', models.IntegerField()),
                ('network_type', models.CharField(choices=[('3G', '3G'), ('4G', '4G'), ('all', 'all')], default='all', max_length=30)),
                ('packageIndicator', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='all', max_length=30)),
                ('ParentPackId', models.IntegerField()),
                ('packValidatyPeriod', models.CharField(choices=[('NoOfDays', 'NoOfDays'), ('NoOfMonths', 'NoOfMonths'), ('NoOfYears', 'NoOfYears')], max_length=30)),
                ('offerDescription', models.TextField()),
                ('actionTobeTaken', models.CharField(choices=[('EndSubscription', 'EndSubscription'), ('AllowStreaming', 'AllowStreaming'), ('other', 'other')], default='other', max_length=30)),
                ('activationReqLaunch', models.CharField(choices=[('WebView', 'WebView'), ('DirectAct', 'DirectAct')], max_length=30)),
                ('partnerId', models.CharField(choices=[('vodafonePlay', 'vodafonePlay'), ('hooq', 'hooq'), ('hungamaPlay', 'hungamaPlay'), ('erosnow', 'erosnow'), ('sonyliv', 'sonyliv')], default='vodafonePlay', max_length=30)),
                ('imgUrl', models.CharField(max_length=60)),
                ('offerImgUrl', models.CharField(max_length=60)),
                ('unsubscription', models.IntegerField()),
                ('actionButtonText', models.CharField(max_length=160)),
                ('iosProductId', models.CharField(max_length=30)),
                ('autoSubscribe', models.IntegerField()),
                ('os', models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('all', 'all')], default='all', max_length=30)),
                ('packStatus', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('closed', 'closed')], default='active', max_length=30)),
                ('targetAudience', models.CharField(choices=[('all', 'all'), ('pack49', 'pack49'), ('pack199', 'pack199'), ('offerA', 'offerA'), ('offerB', 'offerB'), ('offerC', 'offerC'), ('oneplus', 'oneplus'), ('offerD', 'offerD')], default='all', max_length=30)),
                ('offerId', models.CharField(max_length=60)),
                ('cgSmsWifiEnabled', models.IntegerField()),
                ('unsubdescription', models.CharField(max_length=160)),
            ],
        ),
    ]
