# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_smslogin_smspackagedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspackagedetails',
            name='actionButtonText',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='smspackagedetails',
            name='imgUrl',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='smspackagedetails',
            name='iosProductId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='smspackagedetails',
            name='offerImgUrl',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='smspackagedetails',
            name='unsubdescription',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
