from django.db import models
class SMSRegister(models.Model):
    first_name=models.CharField(max_length=40)
    last_name=models.CharField(max_length=40)
    email=models.EmailField()
    password1=models.CharField(max_length=30)
    password2=models.CharField(max_length=30)
class SMSLogin(models.Model):
    email=models.EmailField()
    password=models.CharField(max_length=30)
class SMSPackageDetails(models.Model):
    commertial_choices=(('Buy','Buy'),('TryNBuy','TryNBuy'),('Free','Free'))
    content_choices=(('SD','SD'),('HD','HD'))
    coupansApplicable_choices=(('yes','yes'),('no','no'))
    packType_choices=(('topup','topup'),('standard','standard'),('offer','offer'),('partnerAutoActivate','partnerAutoActivate'),('trialOffer','trialOffer'))
    subscriptionType_choices=(('SVOD','SVOD'),('TVOD','TVOD'))
    packPremium_choices=(('Ad','Ad'),('No Ad','No Ad'))
    consumptionType_choices=(('Stream','Stream'),('Download','Download'),('All','All'))
    downloadType_choices=(('off-peak','off-peak'),('off-line','off-line'),('Immediate','Immediate'))
    network_type_choices=(('3G','3G'),('4G','4G'),('all','all'))
    packageIndicator_choices=(('True','True'),('False','False'))
    packValidatyPeriod_choices=(('NoOfDays','NoOfDays'),('NoOfMonths','NoOfMonths'),('NoOfYears','NoOfYears'))
    actionTobeTaken_choices=(('EndSubscription','EndSubscription'),('AllowStreaming','AllowStreaming'),('other','other'))
    activationReqLaunch_choices=(('WebView','WebView'),('DirectAct','DirectAct'))
    partnerId_choices=(('vodafonePlay','vodafonePlay'),('hooq','hooq'),('hungamaPlay','hungamaPlay'),('erosnow','erosnow'),('sonyliv','sonyliv'))
    os_choices=(('android','android'),('ios','ios'),('all','all'))
    packStatus_choices=(('active','active'),('expired','expired'),('closed','closed'))
    targetAudience_choices=(('all','all'),('pack49','pack49'),('pack199','pack199'),('offerA','offerA'),('offerB','offerB'),('offerC','offerC'),('oneplus','oneplus'),('offerD','offerD'))
    packageId= models.AutoField(primary_key=True)
    packageName=models.CharField(max_length=60)
    commertial_model=models.CharField(choices=commertial_choices,max_length=30,default='Buy')
    contentType=models.CharField(choices=content_choices,max_length=30,default='SD')
    coupansApplicable=models.CharField(choices=content_choices,max_length=30,default='SD')
    startDate= models.DateTimeField(auto_now_add=True)
    endDate=models.DateTimeField(auto_now_add=False)
    duration=models.IntegerField()
    packDuration=models.IntegerField()
    packType=models.CharField(choices=packType_choices,max_length=30,default='topup')
    subscriptionType=models.CharField(choices=subscriptionType_choices,max_length=30,default='SVOD')
    packPremium=models.CharField(choices=packPremium_choices,max_length=30,default='No Ad')
    consumptionType=models.CharField(choices=consumptionType_choices,max_length=30,default='Stream')
    downloadType=models.CharField(choices=downloadType_choices,max_length=30,default='Immediate')
    description=models.TextField()
    packDataValue=models.IntegerField()
    assetGroupId=models.IntegerField()
    network_type=models.CharField(choices=network_type_choices,max_length=30,default='all')
    packageIndicator=models.CharField(choices=packageIndicator_choices,max_length=30,default='all')
    ParentPackId=models.IntegerField()
    packValidatyPeriod=models.CharField(choices=packValidatyPeriod_choices,max_length=30)
    offerDescription=models.TextField()
    actionTobeTaken=models.CharField(choices=actionTobeTaken_choices,max_length=30,default='other')
    activationReqLaunch=models.CharField(choices=activationReqLaunch_choices,max_length=30)
    partnerId=models.CharField(choices=partnerId_choices,max_length=30,default='vodafonePlay')
    imgUrl=models.CharField(max_length=60,null=True)
    offerImgUrl=models.CharField(max_length=60,null=True)
    unsubscription=models.IntegerField()
    actionButtonText=models.CharField(max_length=160,null=True)
    iosProductId=models.CharField(max_length=30,null=True)
    autoSubscribe=models.IntegerField()
    os=models.CharField(choices=os_choices,max_length=30,default='all')
    packStatus=models.CharField(choices=packStatus_choices,max_length=30,default='active')
    targetAudience=models.CharField(choices=targetAudience_choices,max_length=30,default='all')
    offerId=models.CharField(max_length=60)
    cgSmsWifiEnabled=models.IntegerField()
    unsubdescription=models.CharField(max_length=160,null=True)
# Create your models here.
